---

# ------------ PREPARE AND APPLY YAML -------------------------------

- name: Prepare yaml file for CP4WA operator subscription
  template:
    src: cp4wa-operator-subscription.j2
    dest: "{{ status_dir }}/cp4wa/cp4wa-operator-subscription.yml"
  
- name: Display CP4WA operator yaml contents
  command: cat "{{ status_dir }}/cp4wa/cp4wa-operator-subscription.yml"
  register: cp4wa_operator_sub_yaml

- name: Debug CP4WA operator yaml
  debug:
    msg: "{{ cp4wa_operator_sub_yaml.stdout }}"

- name: Create subscription for CP4WA operator
  command: |
    oc apply -f "{{ status_dir }}/cp4wa/cp4wa-operator-subscription.yml"

- name: Wait for CP4WA Orchestrator operator to appear
  community.kubernetes.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    namespace: "{{ current_cp4wa_cluster.project }}"
    label_selectors:
      - operators.coreos.com/ibm-aiops-orchestrator.cp4waiops
  register: orch_subscription
  retries: 15
  delay: 60
  until: ('InstallPlan' in orch_subscription | json_query(condition_query) | unique)
  vars:
    condition_query: 'resources[*].status.installplan.kind'

- name: Wait for CP4WA Orchestrator Deployment to be Available
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Deployment
    namespace: "{{ current_cp4wa_cluster.project }}"
    label_selectors:
      - operators.coreos.com/ibm-aiops-orchestrator.cp4waiops
  register: orch_deployment
  retries: 15
  delay: 20
  until: (['True'] in orch_deployment | json_query(condition_query) | unique )
  vars:
    condition_query: "resources[*].status.conditions[?type == 'Available'].status"
