---
- name: Create temporary directory to hold current global pull secret content
  tempfile:
    state: directory
  register: pull_secret_dir

- name: Extract the global pull secret
  shell: |
    oc extract secret/pull-secret -n openshift-config --confirm --to={{ pull_secret_dir.path }}

- name: Generate secret definition cloud-pak-pull-secret.yaml
  shell: |
    oc create secret generic cloud-pak-pull-secret -n kube-system \
      --from-file=newdockerconfigjson={{ pull_secret_dir.path }}/.dockerconfigjson \
      -o yaml --dry-run=client > {{ status_dir }}/openshift/cloud-pak-pull-secret.yaml

- name: Create secret cloud-pak-pull-secret
  shell: |
    oc apply -f {{ status_dir }}/openshift/cloud-pak-pull-secret.yaml

- name: Generate DaemonSet to set the current pull secret for all nodes
  template:
    src: cloud-pak-pull-secret-ds.j2
    dest: "{{ status_dir }}/openshift/cloud-pak-pull-secret-ds.yaml"
- name: Create or replace DaemonSet cloud-pak-pull-secret-ds
  shell: |
    oc delete ds -n kube-system cloud-pak-pull-secret-ds --ignore-not-found
    oc apply -f {{ status_dir }}/openshift/cloud-pak-pull-secret-ds.yaml