---
- name: Read the global config
  set_fact:
    "{{ _global_config_item.key }}": "{{ _global_config_item.value }}"
  loop: "{{ global_config | dict2items }}"
  loop_control:
    loop_var: _global_config_item