---
- include_role:
    name: cp4wa-variables

- include_tasks: create-catalog-source-ibm-operator-catalog.yml
  when: not _use_case_files

- include_tasks: create-catalog-source-case-file.yml
  when: _use_case_files
