---
- name: 10 - Validate
  hosts: localhost
  connection: local
  become: True
  gather_facts: False

  vars:
    ansible_callback_diy_runner_on_skipped_msg: ""
    ansible_callback_diy_runner_on_ok_msg: ""
    ansible_callback_diy_playbook_on_include_msg: ""

  tasks:

  - name: Load global config
    include_role:
      name: load-global-config

  - name: Load vault config
    include_role:
      name: load-vault-config

  - name: Merge configuration
    include_role:
      name: merge-config
    vars:
      path_to_config_dir: "{{ config_dir }}"
      
  - name: Validate variables
    include_role:
      name: validate-variables

  - name: Lint configuration
    include_role:
      name: lint-config
    vars:
      path_to_generators_dir: "{{ generators_dir | default([(playbook_dir | dirname),'/automation-generators'] | join) }}"